export default [
  {
    id: 1,
    category: 'All',
    icon: 'sports-handball',
    color: '#578ddd',
    TextColor: '#fff',
    SettingText: 'Follow',
    SettingIcon: 'attachment',
  },
  {
    id: 2,
    category: 'raw',
    icon: 'sports-volleyball',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Setting',
    SettingIcon: 'bell',
  },
  {
    id: 3,
    category: 'raw',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Adds',
    SettingIcon: 'browser',
  },
  {
    id: 4,
    category: 'raw',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Account',
    SettingIcon: 'compass',
  },
  {
    id: 5,
    category: 'asd',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'About',
    SettingIcon: 'creative-commons-remix',
  },
];
