export default [
  {
    id: 1,
    category: 'All',
    icon: 'sports-handball',
    color: '#578ddd',
    TextColor: '#fff',
    SettingText: 'Follow',
  },
  {
    id: 2,
    category: 'raw',
    icon: 'sports-volleyball',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Setting',
  },
  {
    id: 3,
    category: 'raw',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Adds',
  },
  {
    id: 4,
    category: 'raw',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'Account',
  },
  {
    id: 5,
    category: 'asd',
    icon: 'sports-soccer',
    color: '#fff',
    TextColor: '#000',
    SettingText: 'About',
  },
];
